import { inter } from "@/app/fonts";

import "@/app/globals.css";
import { authOptions } from "@/auth";
import PrelineScript from "@/components/PrelineScript";
import Navbar from "@/components/home/navbar";
import SessionProvider from "@/context/authContext";
import { LoginProvider } from "@/context/loginContext";
import { ThemeProvider } from "@/context/themeContext";
import { getServerSession } from "next-auth";

require("dotenv").config();

export const metadata = {
  title: "Healt-Guide",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <LoginProvider>
        <body className={`${inter.className} antialiased`}>
          <SessionProvider>
            <ThemeProvider>
              <Navbar />
              {children}
            </ThemeProvider>
          </SessionProvider>
        </body>
      </LoginProvider>
      <PrelineScript />
    </html>
  );
}
