import { inter } from "@/app/fonts";

import PrelineScript from "@/components/PrelineScript";
import Navbar from "@/components/home/navbar";
import { LoginProvider } from "@/context/loginContext";
import { ThemeProvider } from "@/context/themeContext";
import "@/app/globals.css";

require("dotenv").config();
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SessionProvider from "@/context/authContext";

export const metadata = {
  title: "Healt-Guide",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <LoginProvider>
        <body className={`${inter.className} antialiased`}>
          <SessionProvider>

          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
          </SessionProvider>
        </body>
      </LoginProvider>
      <PrelineScript />
    </html>
  );
}
